window.TYR1ONX_MUSIC = [
  {
    id: "sun-earth",
    title: "太阳与地球",
    artist: "卢广仲",
    album: "HeartBreakFast 伤心早餐店",
    year: "2025",
    cover: "./assets/music/covers/sun-earth.svg",
    fallbackCover: "./assets/music/demo-01/cover.webp",
    note: "",
    accent: "#b94f67",
    listenUrl: "https://music.apple.com/cn/album/heartbreakfast-%E5%82%B7%E5%BF%83%E6%97%A9%E9%A4%90%E5%BA%97/1839368226"
  },
  {
    id: "glass",
    title: "玻璃",
    artist: "Gareth.T",
    album: "玻璃 - Single",
    year: "2026",
    cover: "./assets/music/covers/glass.svg",
    fallbackCover: "./assets/music/demo-02/cover.webp",
    note: "",
    accent: "#6f7376",
    listenUrl: "https://music.apple.com/us/song/6769327013"
  },
  {
    id: "regular-friends",
    title: "普通朋友",
    artist: "陶喆",
    album: "I'm O.K.",
    year: "1999",
    cover: "./assets/music/covers/regular-friends.svg",
    fallbackCover: "./assets/music/demo-03/cover.webp",
    note: "",
    accent: "#b89d20",
    listenUrl: "https://music.apple.com/us/song/905206479"
  },
  {
    id: "who-do-you-love",
    title: "爱我还是他",
    artist: "陶喆",
    album: "太平盛世",
    year: "2005",
    cover: "./assets/music/covers/who-do-you-love.svg",
    fallbackCover: "./assets/music/demo-01/cover.webp",
    note: "",
    accent: "#9b553f",
    listenUrl: "https://music.apple.com/us/song/905206660"
  },
  {
    id: "expose",
    title: "拆穿",
    artist: "小霞",
    album: "小霞",
    year: "2015",
    cover: "./assets/music/covers/expose.svg",
    fallbackCover: "./assets/music/demo-02/cover.webp",
    note: "",
    accent: "#8a8a86",
    listenUrl: "https://music.apple.com/us/song/1066174990"
  },
  {
    id: "no-compromise",
    title: "不将就",
    artist: "李荣浩",
    album: "有理想",
    year: "2016",
    cover: "./assets/music/covers/no-compromise.svg",
    fallbackCover: "./assets/music/demo-03/cover.webp",
    note: "",
    accent: "#6c8390",
    listenUrl: "https://www.shazam.com/zh-tw/song/1072339996/%E4%B8%8D%E5%B0%86%E5%B0%B1-%E7%94%B5%E5%BD%B1%E4%BD%95%E4%BB%A5%E7%AC%99%E7%AE%AB%E9%BB%98%E7%89%87%E5%B0%BE%E6%9B%B2"
  },
  {
    id: "engraved-name",
    title: "刻在我心底的名字",
    artist: "卢广仲",
    album: "刻在我心底的名字 - Single",
    year: "2020",
    cover: "./assets/music/covers/engraved-name.svg",
    fallbackCover: "./assets/music/demo-01/cover.webp",
    note: "",
    accent: "#546b91",
    listenUrl: "https://music.apple.com/cn/album/%E5%88%BB%E5%9C%A8%E6%88%91%E5%BF%83%E5%BA%95%E7%9A%84%E5%90%8D%E5%AD%97-%E9%9B%BB%E5%BD%B1-%E5%88%BB%E5%9C%A8%E4%BD%A0%E5%BF%83%E5%BA%95%E7%9A%84%E5%90%8D%E5%AD%97-%E4%B8%BB%E9%A1%8C%E6%9B%B2-single/1528149434"
  },
  {
    id: "love-story-tv",
    title: "Love Story (Taylor’s Version)",
    artist: "Taylor Swift",
    album: "Fearless (Taylor’s Version)",
    year: "2021",
    cover: "./assets/music/covers/love-story-tv.svg",
    fallbackCover: "./assets/music/demo-02/cover.webp",
    note: "",
    accent: "#a77b4d",
    listenUrl: "https://music.apple.com/us/song/1552791427"
  },
  {
    id: "kataomoi",
    title: "カタオモイ",
    artist: "Aimer",
    album: "daydream",
    year: "2016",
    cover: "./assets/music/covers/kataomoi.svg",
    fallbackCover: "./assets/music/demo-03/cover.webp",
    note: "",
    accent: "#7f9fae",
    listenUrl: "https://music.apple.com/us/song/1538259004"
  },
  {
    id: "anxiety",
    title: "Anxiety",
    artist: "Doechii",
    album: "Anxiety - Single",
    year: "2025",
    cover: "./assets/music/covers/anxiety.svg",
    fallbackCover: "./assets/music/demo-01/cover.webp",
    note: "",
    accent: "#66686a",
    listenUrl: "https://music.apple.com/us/song/1800052074"
  },
  {
    id: "tenderness",
    title: "温柔",
    artist: "五月天",
    album: "爱情万岁",
    year: "2000",
    cover: "./assets/music/covers/tenderness.svg",
    fallbackCover: "./assets/music/demo-02/cover.webp",
    note: "",
    accent: "#4a8196",
    listenUrl: "https://music.apple.com/us/song/1078528644"
  },
  {
    id: "mermaid",
    title: "美人鱼",
    artist: "林俊杰",
    album: "第二天堂(江南)",
    year: "2004",
    cover: "./assets/music/covers/mermaid.svg",
    fallbackCover: "./assets/music/demo-03/cover.webp",
    note: "",
    accent: "#7c9295",
    listenUrl: "https://music.apple.com/us/song/1071753633"
  }
];
